// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN3p68BdAL8_imGNBAPP3esifSY1FVjcQ',
    appId: '1:835146719991:web:80498555f9ad3d580ca9f2',
    messagingSenderId: '835146719991',
    projectId: 'speakiq-89598',
    authDomain: 'speakiq-89598.firebaseapp.com',
    databaseURL: 'https://speakiq-89598-default-rtdb.firebaseio.com',
    storageBucket: 'speakiq-89598.appspot.com',
    measurementId: 'G-N6VERNP676',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB33YWBPpQLGsZSPyouKkYNb9KRaleox0',
    appId: '1:835146719991:android:e2d168da6af346a80ca9f2',
    messagingSenderId: '835146719991',
    projectId: 'speakiq-89598',
    databaseURL: 'https://speakiq-89598-default-rtdb.firebaseio.com',
    storageBucket: 'speakiq-89598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVVkibj5fMxvcEgsVPS70MKyrToMiHZOQ',
    appId: '1:835146719991:ios:e49ac4dd20e044f80ca9f2',
    messagingSenderId: '835146719991',
    projectId: 'speakiq-89598',
    databaseURL: 'https://speakiq-89598-default-rtdb.firebaseio.com',
    storageBucket: 'speakiq-89598.appspot.com',
    iosBundleId: 'com.example.speakIq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVVkibj5fMxvcEgsVPS70MKyrToMiHZOQ',
    appId: '1:835146719991:ios:3f680dc65ff6000f0ca9f2',
    messagingSenderId: '835146719991',
    projectId: 'speakiq-89598',
    databaseURL: 'https://speakiq-89598-default-rtdb.firebaseio.com',
    storageBucket: 'speakiq-89598.appspot.com',
    iosBundleId: 'com.example.speakIq.RunnerTests',
  );
}
